LigaAmatorska.Presentation/Controllers/KontoController.cs
using LigaAmatorska.Controllers;
using LigaAmatorska.Presentation.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LigaAmatorska.Presentation.Controllers
{
    public class KontoController : Controller
    {
        [HttpGet]
        public IActionResult Logowanie()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Logowanie(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Haslo == "admin")
                {
                    LoginViewModel.zalogowano = true;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Nieprawidłowa nazwa użytkownika lub hasło");
                }
            }
            return View(model);
        }
    }
}

LigaAmatorska.Presentation/Controllers/TeamController.cs
using LigaAmatorska.Application.Services;
using LigaAmatorska.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace LigaAmatorska.Presentation.Controllers
{
    public class TeamController : Controller
    {
        private readonly IDruzynaService _druzynaService;
        private readonly IWynikiDruzynService _wynikiDruzynService;

        public TeamController(IDruzynaService druzynaService, IWynikiDruzynService wynikiDruzynService)
        {
            _druzynaService = druzynaService;
            _wynikiDruzynService = wynikiDruzynService;
        }

        [HttpGet]
        public IActionResult DodajDruzyne()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> WyswietlWszystkieDruzyny()
        {
            var druzyny = await _druzynaService.GetAllAsync();
            return View(druzyny);
        }

        public IActionResult EdytujDruzyne(int id)
        {
            var druzyna = _druzynaService.GetByIdAsync(id);
            if (druzyna == null)
            {
                return NotFound();
            }
            return View(druzyna);
        }

        [HttpPost]
        public IActionResult EdytujDruzyne(Druzyna druzyna)
        {
            if (ModelState.IsValid)
            {
                //TODO  _druzynaService.Update(druzyna);
                return RedirectToAction("WyswitlWszystkieDruzyny");
            }
            return View(druzyna);
        }

        [HttpPost]
        public async Task<IActionResult> DodajDruzyne(Druzyna druzyna)
        {
            int idWynikowDruzyn = await _wynikiDruzynService.DodajWynikiDruzynAsync(new WynikiDruzyny { });
            await _druzynaService.DodajDruzyneAsync(new Druzyna
            {
                Nazwa = druzyna.Nazwa,
                IdWynikowDruzyny = idWynikowDruzyn
            });
            return RedirectToAction("WyswietlWszystkiedruzyny");
        }

        public async Task<IActionResult> UsunDruzyne(int id)
        {
            var druzyna = await _druzynaService.GetByIdAsync(id);

            return View(druzyna);
        }

        [HttpPost]
        public async Task<IActionResult> UsunDruzyneConfirmed(int id)
        {
            await _druzynaService.RemoveByIdAsync(id);
            return RedirectToAction("WyswietlWszystkieDruzyny");
        }
    }
}

LigaAmatorska.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ligaAmatorska</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ligaAmatorska.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                            <form asp-controller="Konto" asp-action="Logowanie" method="post" class="form-inline">
                                <button type="submit" class="btn btn-link nav-link">Wyloguj</button>
                            </form>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Aktualnosci">Aktualności</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Tabela">Tabela</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Harmonogram">Harmonogram</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="WyswietlWszystkiedruzyny">Zespoły</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Zawodnicy">Zawodnicy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="StronaWBudowie">Statystyki</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-danger text-white" asp-area="" asp-controller="Home" asp-action="StronaWBudowie">Na Żywo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ligaAmatorska - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>